import { VERDICT_META } from "./verdict";
import type { VerificationResult } from "./types";

export function resultToMarkdown(r: VerificationResult): string {
  const lines = [
    `# Claim verification`,
    "",
    `> ${r.claim}`,
    "",
    `**Verdict:** ${VERDICT_META[r.verdict].label} (confidence ${(100 * r.confidence).toFixed(1)}%)`,
    "",
    `| Supported | Contradicted | Insufficient evidence |`,
    `|---|---|---|`,
    `| ${(100 * r.scores.SUPPORTED).toFixed(1)}% | ${(100 * r.scores.CONTRADICTED).toFixed(1)}% | ${(100 * r.scores.INSUFFICIENT_EVIDENCE).toFixed(1)}% |`,
    "",
  ];
  if (r.explanation) lines.push("## Explanation", "", r.explanation, "");
  lines.push("## Evidence", "");
  for (const d of r.documents) {
    const meta = [d.meta?.journal, d.meta?.year].filter(Boolean).join(", ");
    lines.push(`**[${d.citation}] ${d.title}**${meta ? ` — ${meta}` : ""}${d.url ? ` (${d.url})` : ""}`);
    lines.push(`Stance: ${VERDICT_META[d.stance].stance} · evidence weight ${d.evidence_weight.toFixed(2)}`, "");
    for (const e of d.evidence) lines.push(`- "${e.text}" _(rationale ${e.rationale_score.toFixed(2)}, ${VERDICT_META[e.stance].stance})_`);
    lines.push("");
  }
  lines.push(`_Generated by ClaimVerifier AI — ${new Date().toISOString()}_`);
  return lines.join("\n");
}

export function download(filename: string, content: string, type = "text/plain") {
  const url = URL.createObjectURL(new Blob([content], { type }));
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function slug(text: string, n = 48) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, n) || "claim";
}
